# Generated by Django 5.2 on 2025-05-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_shoe_order_price_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='shoe',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
