[project]
name = "dj-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2",
    "django-extensions>=4.1",
    "django-tailwind>=4.0.1",
    "pillow>=11.2.1",
    "stripe>=12.1.0",
]
